# Generated by Django 5.1.6 on 2025-03-25 05:02

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmacia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('contacto_principal', models.CharField(max_length=255)),
                ('email_contacto', models.EmailField(max_length=254)),
                ('telefono_contacto', models.CharField(max_length=15)),
                ('cuit', models.CharField(max_length=15)),
                ('drogueria', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LiquidacionGaleno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prestador', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('orden_de_pago', models.CharField(max_length=50, unique=True)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=15)),
                ('retenciones', models.DecimalField(decimal_places=2, max_digits=15)),
                ('credito', models.DecimalField(decimal_places=2, max_digits=20)),
                ('liquidacion', models.CharField(max_length=50)),
                ('importe_liquidado', models.DecimalField(decimal_places=2, max_digits=20)),
                ('archivo_origen', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='custom_user_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_set', to='auth.permission', verbose_name='user permissions')),
                ('farmacia', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.farmacia')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CargaDatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obra_social', models.CharField(choices=[('OSDIPP', 'OSDIPP'), ('SWISS_MEDICAL', 'Swiss Medical'), ('GALENO', 'Galeno'), ('FARMALINK', 'Farmalink'), ('PAMI', 'PAMI'), ('PAMI_ONCOLOGICO', 'PAMI Oncológico'), ('PAMI_NUTRICIONALES', 'PAMI Nutricionales'), ('PAMI_PAÑALES', 'PAMI Pañales'), ('AVALIAN', 'Avalian'), ('ART', 'ART Varias')], max_length=50)),
                ('periodo', models.CharField(max_length=20)),
                ('numero_presentacion', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(choices=[('Enviada', 'Enviada'), ('Recibida', 'Recibida'), ('Presentada', 'Presentada'), ('Liquidada', 'Liquidada')], default='Enviada', max_length=20)),
                ('cantidad_lotes', models.IntegerField(blank=True, null=True)),
                ('cantidad_recetas', models.IntegerField(blank=True, null=True)),
                ('importe_100', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('importe_a_cargo', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('total_pvp', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('total_pvp_pami', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('importe_bruto_convenio', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('codigo_facaf', models.CharField(blank=True, max_length=20, null=True)),
                ('codigo_farmalink', models.CharField(blank=True, max_length=20, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('farmacia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.farmacia')),
            ],
        ),
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obra_social', models.CharField(max_length=50)),
                ('periodo', models.CharField(max_length=20)),
                ('cantidad_recetas', models.IntegerField()),
                ('importe_100', models.DecimalField(decimal_places=2, max_digits=10)),
                ('importe_a_cargo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_pvp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('archivo_origen', models.CharField(blank=True, max_length=20, null=True)),
                ('farmacia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.farmacia')),
            ],
        ),
        migrations.CreateModel(
            name='LiquidacionJerarquicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_farmacia', models.CharField(help_text='Código de la farmacia', max_length=20)),
                ('nombre_farmacia', models.CharField(help_text='Nombre de la farmacia', max_length=255)),
                ('plan', models.CharField(help_text='Plan de la obra social', max_length=255)),
                ('fecha_liquidacion', models.DateField(help_text='Fecha de la liquidación')),
                ('importe_100', models.DecimalField(decimal_places=2, help_text='Importe total de la presentación', max_digits=15)),
                ('a_cargo_os', models.DecimalField(decimal_places=2, help_text='Importe a cargo de la obra social', max_digits=15)),
                ('bonificacion', models.DecimalField(decimal_places=2, help_text='Bonificación aplicada', max_digits=15)),
                ('nota_credito', models.DecimalField(decimal_places=2, help_text='Nota de crédito aplicada', max_digits=15)),
                ('subtotal_pagar', models.DecimalField(decimal_places=2, help_text='Subtotal a pagar', max_digits=15)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('archivo_origen', models.CharField(blank=True, max_length=20, null=True)),
                ('farmacia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidaciones_jerarquicos', to='core.farmacia')),
            ],
            options={
                'verbose_name': 'Liquidación Jerárquicos',
                'verbose_name_plural': 'Liquidaciones Jerárquicos',
            },
        ),
        migrations.CreateModel(
            name='LiquidacionPAMI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_farmacia', models.CharField(help_text='Código de la farmacia en PAMI', max_length=20)),
                ('nombre_farmacia', models.CharField(help_text='Nombre de la farmacia', max_length=255)),
                ('plan', models.CharField(help_text='Plan de la obra social', max_length=255)),
                ('fecha_liquidacion', models.DateField(help_text='Fecha en la que se procesó la liquidación')),
                ('importe_100', models.DecimalField(decimal_places=2, help_text='Importe total de la presentación', max_digits=15)),
                ('a_cargo_os', models.DecimalField(decimal_places=2, help_text='Importe a cargo de la obra social', max_digits=15)),
                ('bonificacion', models.DecimalField(decimal_places=2, help_text='Bonificación aplicada', max_digits=15)),
                ('nota_credito', models.DecimalField(decimal_places=2, help_text='Nota de crédito aplicada', max_digits=15)),
                ('subtotal_pagar', models.DecimalField(decimal_places=2, help_text='Subtotal a pagar', max_digits=15)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('archivo_origen', models.CharField(blank=True, max_length=20, null=True)),
                ('farmacia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidaciones_pami', to='core.farmacia')),
            ],
            options={
                'verbose_name': 'Liquidación PAMI',
                'verbose_name_plural': 'Liquidaciones PAMI',
            },
        ),
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('obra_social', models.CharField(choices=[('OSDIPP', 'OSDIPP'), ('SWISS_MEDICAL', 'Swiss Medical'), ('GALENO', 'Galeno'), ('FARMALINK', 'Farmalink'), ('PAMI', 'PAMI'), ('AVALIAN', 'Avalian')], max_length=50)),
                ('quincena', models.CharField(choices=[('1', 'Primera'), ('2', 'Segunda')], max_length=1)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
