# Generated by Django 5.1.5 on 2025-04-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmacia',
            name='codigo_farmacia',
            field=models.CharField(default='F000', help_text='Código de la farmacia', max_length=20),
        ),
    ]
