# Generated by Django 5.1.5 on 2025-04-22 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_farmacia_codigo_farmacia'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmacia',
            name='cbu',
            field=models.CharField(default='00000000000000000000', max_length=15),
        ),
    ]
