# Generated by Django 5.1.6 on 2025-04-24 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_farmacia_cbu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmacia',
            name='cbu',
            field=models.CharField(default='000000000000000', max_length=55),
        ),
    ]
