# Generated by Django 5.1.6 on 2025-03-31 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_liquidacionosfatlyf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liquidacionosfatlyf',
            name='subtotal_pagar',
        ),
    ]
