# Generated by Django 5.1.6 on 2025-04-30 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_farmacia_cbu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentacion',
            name='quincena',
            field=models.CharField(choices=[('1', 'Primera'), ('2', 'Segunda'), ('mensual', 'Mensual')], max_length=40),
        ),
    ]
