# Generated by Django 5.1.6 on 2025-04-30 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_presentacion_quincena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargadatos',
            name='cantidad_lotes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cargadatos',
            name='cantidad_recetas',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cargadatos',
            name='codigo_facaf',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cargadatos',
            name='codigo_farmalink',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cargadatos',
            name='importe_100',
            field=models.DecimalField(decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='cargadatos',
            name='importe_a_cargo',
            field=models.DecimalField(decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='cargadatos',
            name='importe_bruto_convenio',
            field=models.DecimalField(decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='cargadatos',
            name='numero_presentacion',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cargadatos',
            name='periodo',
            field=models.DateField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cargadatos',
            name='total_pvp',
            field=models.DecimalField(decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='cargadatos',
            name='total_pvp_pami',
            field=models.DecimalField(decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='cargadatos',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
