# Generated by Django 5.1.6 on 2025-03-31 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_liquidacionpamioncologico'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiquidacionPAMIPanales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_farmacia', models.CharField(help_text='Código de la farmacia en PAMI', max_length=20)),
                ('nombre_farmacia', models.CharField(help_text='Nombre de la farmacia', max_length=255)),
                ('plan', models.CharField(help_text='Plan de la obra social', max_length=255)),
                ('fecha_liquidacion', models.DateField(help_text='Fecha en la que se procesó la liquidación')),
                ('importe_100', models.DecimalField(decimal_places=2, help_text='Importe total de la presentación', max_digits=15)),
                ('a_cargo_os', models.DecimalField(decimal_places=2, help_text='Importe a cargo de la obra social', max_digits=15)),
                ('bonificacion', models.DecimalField(decimal_places=2, help_text='Bonificación aplicada', max_digits=15)),
                ('nota_credito', models.DecimalField(decimal_places=2, help_text='Nota de crédito aplicada', max_digits=15)),
                ('subtotal_pagar', models.DecimalField(decimal_places=2, help_text='Subtotal a pagar', max_digits=15)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('archivo_origen', models.CharField(blank=True, max_length=20, null=True)),
                ('farmacia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidaciones_pami_panales', to='core.farmacia')),
            ],
            options={
                'verbose_name': 'Liquidación PAMI Pañales',
                'verbose_name_plural': 'Liquidaciones PAMI Pañales',
            },
        ),
    ]
