# Generated by Django 5.1.6 on 2025-04-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_cargadatos_cantidad_lotes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargadatos',
            name='periodo',
            field=models.DateTimeField(max_length=20),
        ),
    ]
