# Generated by Django 5.1.6 on 2025-04-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_cargadatos_periodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargadatos',
            name='periodo',
            field=models.DateField(max_length=20),
        ),
    ]
