# Generated by Django 5.1.6 on 2025-05-12 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_cargadatos_periodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquidacion',
            name='archivo_origen',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='liquidacionandinaart',
            name='archivo_origen',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='liquidacionasociart',
            name='archivo_origen',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='liquidacioncoloniasuiza',
            name='archivo_origen',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='liquidacionexperta',
            name='archivo_origen',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='liquidaciongaleno',
            name='archivo_origen',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='liquidaciongalenoart',
            name='archivo_origen',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='liquidacionjerarquicos',
            name='archivo_origen',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='liquidacionosfatlyf',
            name='archivo_origen',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='liquidacionospil',
            name='archivo_origen',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='liquidacionpami',
            name='archivo_origen',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='liquidacionpamioncologico',
            name='archivo_origen',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='liquidacionpamipanales',
            name='archivo_origen',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='liquidacionpamivacunas',
            name='archivo_origen',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='liquidacionprevencionart',
            name='archivo_origen',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
