# Generated by Django 5.1.6 on 2025-03-31 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_liquidacionasociart'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiquidacionColoniaSuiza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_farmacia', models.CharField(max_length=20)),
                ('nombre_farmacia', models.CharField(max_length=255)),
                ('plan', models.CharField(max_length=255)),
                ('fecha_liquidacion', models.DateField()),
                ('importe_100', models.DecimalField(decimal_places=2, max_digits=15)),
                ('a_cargo_os', models.DecimalField(decimal_places=2, max_digits=15)),
                ('bonificacion', models.DecimalField(decimal_places=2, max_digits=15)),
                ('nota_credito', models.DecimalField(decimal_places=2, max_digits=15)),
                ('subtotal_pagar', models.DecimalField(decimal_places=2, max_digits=15)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('archivo_origen', models.CharField(blank=True, max_length=20, null=True)),
                ('farmacia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidaciones_coloniasuiza', to='core.farmacia')),
            ],
            options={
                'verbose_name': 'Liquidación Colonia Suiza',
                'verbose_name_plural': 'Liquidaciones Colonia Suiza',
            },
        ),
    ]
