# Generated by Django 5.1.6 on 2025-05-25 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_liquidacion_archivo_origen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargadatos',
            name='periodo',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
