# Generated by Django 5.1.6 on 2025-06-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_cargadatos_periodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargadatos',
            name='estado',
            field=models.CharField(choices=[('Enviado', 'Enviado'), ('Recibida en Cámara', 'Recibido en Cámara'), ('Presentado en obra social', 'Presentado en obra social'), ('Liquidada', 'Liquidada')], default='Enviada', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_facaf',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
