# Generated by Django 5.1.6 on 2025-06-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_cargadatos_estado_alter_user_id_facaf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargadatos',
            name='periodo',
            field=models.DateField(default='none', max_length=50),
        ),
    ]
