# Generated by Django 5.1.6 on 2025-07-10 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_publication_publicationcomment_publicationlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationcomment',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Indica si el comentario fue eliminado (borrado lógico)'),
        ),
        migrations.AddField(
            model_name='publicationcomment',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Comentario padre si es una respuesta', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.publicationcomment'),
        ),
    ]
