# Generated by Django 5.1.6 on 2025-03-31 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_liquidacionprevencionart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargadatos',
            name='obra_social',
            field=models.CharField(choices=[('OSDIPP', 'OSDIPP'), ('SWISS_MEDICAL', 'Swiss Medical'), ('GALENO', 'Galeno'), ('Ospilampil', 'OspilAmpil'), ('Osfatlyf', 'Osfatlyf'), ('Jerarquicos', 'Jerarquicos Salud'), ('PAMI', 'PAMI'), ('PAMI_ONCOLOGICO', 'PAMI Oncológico'), ('PAMI_VACUNAS', 'PAMI Vacunas'), ('PAMI_PAÑALES', 'PAMI Pañales'), ('AVALIAN', 'Avalian'), ('Andrina_ART', 'Andina ART'), ('Asociart_ART', 'Asociart ART'), ('Coloniasuiza', 'Colonia Suiza'), ('experta_ART', 'Experta ART'), ('Galeno_ART', 'Galeno ART'), ('LaSegunda_ART', 'La Segunda ART'), ('Prevencion_ART', 'Prevencion ART')], max_length=50),
        ),
    ]
