# Generated by Django 5.1.6 on 2025-07-10 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_reclamo'),
        ('core', '0014_publicationcomment_is_deleted_and_more'),
    ]

    operations = [
    ]
