# Generated by Django 5.1.6 on 2025-07-10 09:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_merge_20250710_0600'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamo',
            name='asignados',
            field=models.ManyToManyField(blank=True, help_text='Usuarios asignados a este reclamo (múltiples)', related_name='reclamos_asignados_multiple', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reclamo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
