# Generated by Django 5.1.6 on 2025-07-13 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuiaArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título del archivo', max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del archivo')),
                ('categoria', models.CharField(choices=[('manual', 'Manual'), ('procedimiento', 'Procedimiento'), ('formulario', 'Formulario'), ('guia', 'Guía'), ('faq', 'Preguntas Frecuentes'), ('otro', 'Otro')], default='manual', max_length=20)),
                ('estado', models.CharField(choices=[('publico', 'Público'), ('privado', 'Privado')], default='publico', max_length=10)),
                ('archivo', models.FileField(help_text='Archivo (PDF, Word, Excel, etc.)', upload_to='guias/archivos/')),
                ('tipo_archivo', models.CharField(choices=[('pdf', 'PDF'), ('doc', 'Word'), ('docx', 'Word'), ('xls', 'Excel'), ('xlsx', 'Excel'), ('ppt', 'PowerPoint'), ('pptx', 'PowerPoint'), ('txt', 'Texto'), ('otro', 'Otro')], default='pdf', max_length=10)),
                ('tamanio', models.BigIntegerField(blank=True, help_text='Tamaño del archivo en bytes', null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('descargas', models.PositiveIntegerField(default=0, help_text='Número de descargas')),
                ('visualizaciones', models.PositiveIntegerField(default=0, help_text='Número de visualizaciones')),
                ('usuario', models.ForeignKey(help_text='Usuario que subió el archivo', on_delete=django.db.models.deletion.CASCADE, related_name='archivos_subidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archivo de Guía',
                'verbose_name_plural': 'Archivos de Guías',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='GuiaVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título del video', max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del video')),
                ('categoria', models.CharField(choices=[('tutorial', 'Tutorial'), ('manual', 'Manual'), ('explicacion', 'Explicación'), ('demo', 'Demostración'), ('otro', 'Otro')], default='tutorial', max_length=20)),
                ('estado', models.CharField(choices=[('publico', 'Público'), ('privado', 'Privado')], default='publico', max_length=10)),
                ('archivo_video', models.FileField(help_text='Archivo de video (MP4, AVI, MOV, etc.)', upload_to='guias/videos/')),
                ('thumbnail', models.ImageField(blank=True, help_text='Imagen de vista previa del video', null=True, upload_to='guias/thumbnails/')),
                ('duracion', models.CharField(blank=True, help_text='Duración del video (HH:MM:SS)', max_length=10)),
                ('tamanio', models.BigIntegerField(blank=True, help_text='Tamaño del archivo en bytes', null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('visualizaciones', models.PositiveIntegerField(default=0, help_text='Número de visualizaciones')),
                ('descargas', models.PositiveIntegerField(default=0, help_text='Número de descargas')),
                ('usuario', models.ForeignKey(help_text='Usuario que subió el video', on_delete=django.db.models.deletion.CASCADE, related_name='videos_subidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Video de Guía',
                'verbose_name_plural': 'Videos de Guías',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
