# Generated by Django 5.1.6 on 2025-07-13 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_guiaarchivo_guiavideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guiavideo',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Imagen de vista previa generada automáticamente del video', null=True, upload_to='guias/thumbnails/'),
        ),
    ]
