# Generated by Django 5.1.6 on 2025-07-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_guiavideo_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacionospil',
            name='credito',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='liquidacionospil',
            name='debitos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='liquidacionospil',
            name='gastos_debitos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='liquidacionospil',
            name='recuperacion_gastos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
