# Generated by Django 5.1.6 on 2025-07-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_liquidacionospil_credito_liquidacionospil_debitos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidaciongalenoart',
            name='credito',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='liquidaciongalenoart',
            name='debitos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='liquidaciongalenoart',
            name='gastos_debitos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='liquidaciongalenoart',
            name='recuperacion_gastos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
