# Generated by Django 5.1.6 on 2025-07-14 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_liquidacionjerarquicos_credito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacionosfatlyf',
            name='ajustes',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='liquidacionosfatlyf',
            name='debitos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='liquidacionosfatlyf',
            name='recuperacion_ajustes',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='liquidacionosfatlyf',
            name='recuperacion_gastos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='liquidacionosfatlyf',
            name='subtotal_a_pagar',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
