# Generated by Django 5.1.6 on 2025-07-14 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_liquidacionasociart_ajustes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacionexperta',
            name='ajustes',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='liquidacionexperta',
            name='debitos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='liquidacionexperta',
            name='recuperacion_ajustes',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='liquidacionexperta',
            name='recuperacion_gastos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
