# Generated by Django 5.1.6 on 2025-07-14 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_liquidacionexperta_ajustes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiquidacionLaSegundaART',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_farmacia', models.CharField(max_length=20)),
                ('nombre_farmacia', models.CharField(max_length=255)),
                ('plan', models.CharField(max_length=255)),
                ('fecha_liquidacion', models.DateField()),
                ('importe_100', models.DecimalField(decimal_places=2, max_digits=15)),
                ('a_cargo_os', models.DecimalField(decimal_places=2, max_digits=15)),
                ('bonificacion', models.DecimalField(decimal_places=2, max_digits=15)),
                ('nota_credito', models.DecimalField(decimal_places=2, max_digits=15)),
                ('subtotal_pagar', models.DecimalField(decimal_places=2, max_digits=15)),
                ('debitos', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('credito', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('gastos_debitos', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('recuperacion_gastos', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('archivo_origen', models.CharField(blank=True, max_length=50, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('farmacia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidaciones_lasegundaart', to='core.farmacia')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liquidaciones_lasegundaart', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Liquidación La Segunda ART',
                'verbose_name_plural': 'Liquidaciones La Segunda ART',
            },
        ),
    ]
