# Generated by Django 5.1.6 on 2025-07-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_liquidacionandinaart_ajustes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacionpami',
            name='creditos',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Créditos OS', max_digits=15),
        ),
        migrations.AddField(
            model_name='liquidacionpami',
            name='debitos',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Débitos OS', max_digits=15),
        ),
        migrations.AddField(
            model_name='liquidacionpami',
            name='inst_pago_drogueria',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Inst. Pago Droguería', max_digits=15),
        ),
        migrations.AddField(
            model_name='liquidacionpami',
            name='recuperacion_gastos',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Recupero Gastos', max_digits=15),
        ),
    ]
