# Generated by Django 5.1.6 on 2025-07-14 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_liquidacionpami_creditos_liquidacionpami_debitos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacionpamioncologico',
            name='ajustes',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='liquidacionpamioncologico',
            name='debitos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='liquidacionpamioncologico',
            name='recuperacion_ajustes',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='liquidacionpamioncologico',
            name='recuperacion_gastos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='liquidacionpamipanales',
            name='ajustes',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='liquidacionpamipanales',
            name='debitos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='liquidacionpamipanales',
            name='recuperacion_ajustes',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='liquidacionpamipanales',
            name='recuperacion_gastos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='liquidacionpamivacunas',
            name='ajustes',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='liquidacionpamivacunas',
            name='debitos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='liquidacionpamivacunas',
            name='recuperacion_ajustes',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='liquidacionpamivacunas',
            name='recuperacion_gastos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
