# Generated by Django 5.1.6 on 2025-07-14 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_liquidacionpamioncologico_ajustes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiquidacionOSDIPP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_farmacia', models.CharField(help_text='Código de la farmacia', max_length=20)),
                ('nombre_farmacia', models.CharField(help_text='Nombre de la farmacia', max_length=255)),
                ('plan', models.CharField(default='OSDIPP', help_text='Plan de la obra social', max_length=255)),
                ('fecha_liquidacion', models.DateField(help_text='Fecha de la liquidación')),
                ('recetas_presentadas', models.IntegerField(default=0)),
                ('importe_total_presentado', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('importe_entregado_presentado', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('recetas_aceptadas', models.IntegerField(default=0)),
                ('importe_total_aceptado', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('importe_entregado_aceptado', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('aporte_farmacia', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('gastos_auditoria', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('importe_neto', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('gastos_recs', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('ajustes_anteriores', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('ajuste_credito_anticipado', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('importe_a_pagar', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('importe_efectivo', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('ajustes_posteriores', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('archivo_origen', models.CharField(blank=True, max_length=50, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('farmacia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidaciones_osdipp', to='core.farmacia')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liquidaciones_osdipp', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Liquidación OSDIPP',
                'verbose_name_plural': 'Liquidaciones OSDIPP',
            },
        ),
    ]
