# Generated by Django 5.1.6 on 2025-07-16 08:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_liquidacionosdipp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargadatos',
            name='periodo',
        ),
        migrations.AddField(
            model_name='cargadatos',
            name='periodo_desde',
            field=models.DateField(default=datetime.date.today, help_text='Periodo desde'),
        ),
        migrations.AddField(
            model_name='cargadatos',
            name='periodo_hasta',
            field=models.DateField(default=datetime.date.today, help_text='Periodo hasta'),
        ),
    ]
